### Importing Trainer API and datasets API

In [4]:
from transformers import trainer

In [5]:
!pip install datasets

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 491.2/491.2 kB 8.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 11.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.9/183.9 kB 13.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 10.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 15.2 MB/s eta 0:00:00
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.3.2
    Uninstalling fsspec-2025.3.2:
      Successfully uninstalled fsspec-2025.3.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2025.3.2 requires fsspec==2025.3.2, but you have fsspec 2024.12.0 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cublas-cu12==12.4.5.8; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cublas-cu12 12.5.3.2 which 

### HF Abstraction:

Performing abstract operations using LLM classess for creating low code ML workflows:

- Below are the classes I'll be using to perform text classification and sentiment analysis by using libraries and models provided by hugging face.

### Libraries Used

1.  pretrainedclassifier
2.  Datasets
3.  Trainer API
4.  GLUE benchmark datasets (MRPC for this particular case)


In [48]:
### Creating variable clsmodel from model card of BERT pretrained classification model on HF
from transformers import AutoModelForSequenceClassification
model_checkpoint= "distilbert-base-uncased-finetuned-sst-2-english"

In [49]:
cls_model = AutoModelForSequenceClassification.from_pretrained(model_checkpoint)

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

In [55]:
print(cls_model)

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)


In [19]:
## Inititalizing input for text classification
input= [
    "An apple a day keeps the doctor away",
    "May the force be with you",
    "The delicious cow said Mooooorgh....."
]

> Before importing textclassificationpipeline, a suitable tokenizer also needs to be initiated, so we'll be using distil-berts model only for initiating our tokenizer

In [57]:
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

In [59]:
# Importing textclassificationpipeline library

from transformers import TextClassificationPipeline

classifier = TextClassificationPipeline(model=cls_model, tokenizer=tokenizer)

Device set to use cpu


In [61]:
classifier(input)

[{'label': 'NEGATIVE', 'score': 0.9442117810249329},
 {'label': 'POSITIVE', 'score': 0.9985313415527344},
 {'label': 'POSITIVE', 'score': 0.999565064907074}]

### Pipeline API

`Pipelines` are a great way of using models for inference. Pipelines are objects that abstract the code of a library, These pipelines can be used for a huge variety of tasks such as `text-generation`, `sentiment-analysis`, `feature-extraction`, `q&a generation` etc.

1.  `Pipelines` API is the most powerful api, as it contains all other pipelines used for performing tasks.

In [72]:
# Import pipelines library
from transformers import pipeline

In [73]:
classifier = pipeline('text-classification')

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cpu


In [74]:
classifier(input)

[{'label': 'NEGATIVE', 'score': 0.9442117810249329},
 {'label': 'POSITIVE', 'score': 0.9985313415527344},
 {'label': 'POSITIVE', 'score': 0.999565064907074}]

In [75]:
generator= pipeline('text-generation')

No model was supplied, defaulted to openai-community/gpt2 and revision 607a30d (https://huggingface.co/openai-community/gpt2).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Device set to use cpu


In [76]:
?generator

In [ ]:
merged.drop_duplicates()

c   d   a   b
0   1   2   1   2
1   2   3   2   3
2   3   4   3   4
3   4   5   4   5
4   5   6   5   6
5   6   7   6   7
6   7   8   7   8
7   8   9   8   9
8   9  10   9  10
9  10  11  10  11

![image.png](attachment:image.png)

In [ ]:
array = np.array([i for i in range(1, 31)])
array = array.reshape((5,6))
array

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

**dtype & itemsize**

In [ ]:
array.dtype

dtype('int32')

**itemsize**: returns the size of an element in bytes

In [ ]:
print(array.itemsize, "bytes")

**size**: returns the size of an array as number of elements in it.

In [ ]:
print(array.size, "elements")

16 elements


**nbytes**: returns the size of an array in bytes.

In [ ]:
# Get total size #
print("size of array =", array.size*array.itemsize, " bytes")

size of array = 64  bytes


In [ ]:
# Get total size of array using nbytes #
print("size of array =", array.nbytes, " bytes")

size of array = 64  bytes


- **ndim**: returns the dimension of array.
- **shape**: returns the shape of an ndim array.

In [ ]:
# Scoping basic information of an array #
print("dimension: ",array.ndim)
print("shape: ",array.shape)
print("size: ",array.size)

dimension:  2
shape:  (8, 2)
size:  16


## Initializing numpy array

**Ones**: an array of ones

In [ ]:
arrone = np.ones([5, 6])
arrone

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

**Zeros**: an array of zeros.

In [ ]:
arrzero = np.zeros([5, 6])
arrzero

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

**Eye**: an array with 1s on the specified diagonal and 0s elsewhere

In [ ]:
arreye = np.eye(6, 4, -3)
arreye

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

**Arange**: arange method is similar to range method in standard python. The arange method in numpy creates an array with the same elements as the range datatype. Unlike the range datatype, this is stored as an array.

np.arange(start_, stop_, step_size)


In [ ]:
arrange = np.arange(2, 4, 0.125)
arrange

array([2.   , 2.125, 2.25 , 2.375, 2.5  , 2.625, 2.75 , 2.875, 3.   ,
       3.125, 3.25 , 3.375, 3.5  , 3.625, 3.75 , 3.875])

**Linspace**: The linspace method divides the given endpoints into specified number of equally spaced intervals.

In [ ]:
arrlinspace = np.linspace(2, 4, 16)
arrlinspace


array([2.        , 2.13333333, 2.26666667, 2.4       , 2.53333333,
       2.66666667, 2.8       , 2.93333333, 3.06666667, 3.2       ,
       3.33333333, 3.46666667, 3.6       , 3.73333333, 3.86666667,
       4.        ])

**Empty**: The empty method creates an array with very small values,
of specified shape

np.empty((rows_, columns_))

In [ ]:
arrempty = np.empty((6, 4))
arrempty

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

**Full**: The full method creates an array where each element contains the same value.

np.full(a_shape, fill_value)

In [ ]:
arrfull = np.full((6, 4), 11)
arrfull

array([[11, 11, 11, 11],
       [11, 11, 11, 11],
       [11, 11, 11, 11],
       [11, 11, 11, 11],
       [11, 11, 11, 11],
       [11, 11, 11, 11]])

**full_like**: Creates an array with size equal to the array supplied and fills it with the mentioned value.

In [ ]:
arrflike = np.full_like(arrfull, 7)
arrflike

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [ ]:
print(arrfull.shape)
print(arrflike.shape)

(6, 4)
(6, 4)


**Copy**: Numpy arrays can not equated for copying their contents instead np.copy method is used to create copies of numpy arrays.

np.copy(array)

In [ ]:
arrcopy = np.copy(arrfull)
arrcopy

array([[11, 11, 11, 11],
       [11, 11, 11, 11],
       [11, 11, 11, 11],
       [11, 11, 11, 11],
       [11, 11, 11, 11],
       [11, 11, 11, 11]])

**Geomspace**: The geomspace method also creates an evenly spaced array between two end points like linspace but produces values evenly spaced on a log scale.

    np.geomspace(start_, stop_, no_of_elements)

In [ ]:
arrgeom = np.geomspace(1, 2, 5)
arrgeom

array([1.        , 1.18920712, 1.41421356, 1.68179283, 2.        ])

**rng (Random Number Generator)**: Firstly we have to create a random number generator by using
    
    np.random.default_rng()
and then we can generate random numbers according to the parameters specified. By default rng.random() code will generate random float between 0 and 1

In [ ]:
rng = np.random.default_rng()

In [ ]:
rng.random()

0.6494312566681211

an array of random values can be generated by passing an integer the function

In [ ]:
rng.random(10)

array([0.27246657, 0.84990597, 0.77390204, 0.18760376, 0.7780076 ,
       0.07961651, 0.63467208, 0.39341191, 0.20106829, 0.54364938])

**integers**: by default rng.random() generates random float values. We can use rng.integers() method to generate integer values

rng.integers(start_ , stop_ , no_of_values)

In [ ]:
rng.integers(1, 100, 50)

array([23, 54, 41, 61, 53, 35, 62, 91, 48, 92, 41, 68, 10, 65, 83, 94, 66,
       72, 93, 79, 99, 61, 84, 17, 37, 70, 18, 57, 55, 53, 69, 96, 78, 35,
       97, 49,  4, 66, 13, 73, 77, 97, 82, 87, 71, 14,  5, 22, 99, 38],
      dtype=int64)

**repeat**: There are mulitple ways of applying numpy.repeat function
    
    -np.repeat(value, x_times)
    -np.repeat(value_list, x_times)
    -np.repeat(value_list, x_times_list)

In [ ]:
arrepeat = np.repeat(25, 5)
arrepeat

array([25, 25, 25, 25, 25])

In [ ]:
arrepeat2 = np.repeat([25, 50, 75], 4)
arrepeat2

array([25, 25, 25, 25, 50, 50, 50, 50, 75, 75, 75, 75])

In [ ]:
arrepeat3 = np.repeat([25, 50 ,70], [2, 5 ,7])
arrepeat3

array([25, 25, 50, 50, 50, 50, 50, 70, 70, 70, 70, 70, 70, 70])

In [ ]:
arr = np.random.randn(1,3)
arrepeat4 = np.repeat(arr, 3, axis = 1)
arrepeat4

array([[ 0.93747971,  0.93747971,  0.93747971,  0.6327562 ,  0.6327562 ,
         0.6327562 , -0.79288742, -0.79288742, -0.79288742]])

**Random number generators**:

The **numpy.random** module implements pseudo-random number generators (PRNGs) or random numbe generators (RNGs) with the ability to draw samples from a variety of distributions. In general, a user creates a generator instance with default_rng and calls the various methods on it to obtain samples from different distributions.

In [ ]:
rng = np.random.default_rng()
rng.random(10).reshape(5, 2)

array([[0.84311407, 0.49859486],
       [0.80452868, 0.05227964],
       [0.11990208, 0.71198728],
       [0.66540231, 0.87168639],
       [0.76809183, 0.84889362]])

In [ ]:
prng = np.random

**rand**: Random values in given shape create a random array of the given shape and populate it with random samples from a uniform distribution over [0, 1).


In [ ]:
prng.rand(5, 2)

array([[0.29058654, 0.12117237],
       [0.24151672, 0.20627739],
       [0.53323913, 0.74326435],
       [0.25219902, 0.63957953],
       [0.77071689, 0.62480638]])

**randn**: Return a sample (or samples) from the standard normal distribution.

- if positive int_like arguments are provided, randn generates an array of shape (d0, d1, d2, d3, d4, ....., dn) with float values from a univariate "Normal" (Gaussian) distribution with mean 0 and variance 1.
- a single float from the distribution is returned if no argument is provided.


In [ ]:
prng.randn(5, 2)

array([[ 1.03297629,  0.07897382],
       [-1.66513018,  0.56648213],
       [-1.06531266, -2.01650085],
       [ 0.05720545,  1.16170356],
       [-2.27498635, -0.61755645]])

**randint**: method return random integers from low(inclusive) to high(exclusive).
- This method return random integers from the "discrete uniform distribution" of the specified dtype in the half open interval [low, high).

- If high is None(default), then result are from [0, low).

In [ ]:
arr = prng.randint(low = 10, high = 100, size = (5, 2))
pd.DataFrame(arr)

0   1
0  11  27
1  36  54
2  37  70
3  54  79
4  78  70

**random_integers** method returns random integers of type np.int_ between low and high, inclusive.
- This method returns random integers of type np.int_ from a discrete uniform distribution in the closed interval [low, high]. If high is None(the default), then results are from [0, low].
- The np.int_ type translated to the C long integer type and it's precision is platform dependent.

In [ ]:
prng.random_integers(low = 5, high = 75, size = (5, 5))

C:\Users\death\AppData\Local\Temp\ipykernel_21628\1886848010.py:1: DeprecationWarning: This function is deprecated. Please call randint(5, 75 + 1) instead
  prng.random_integers(low = 5, high = 75, size = (5, 5))


array([[23, 19, 36, 57, 18],
       [75, 15, 48, 62, 17],
       [41, 59,  9, 43, 30],
       [39, 60, 67, 26, 17],
       [28, 75, 41, 69, 43]])

**random_sample**: returns random floats in the half-interval [0.0, 1.0).

- Results are from the "continuous uniform" distribution over the stated interval.

In [ ]:
prng.random_sample((5,5))

array([[0.70815706, 0.30207376, 0.31902207, 0.58602635, 0.0797347 ],
       [0.33391948, 0.04642185, 0.39796997, 0.76007574, 0.54828155],
       [0.15741131, 0.45870451, 0.74499956, 0.60510878, 0.27693082],
       [0.95876141, 0.3134844 , 0.87541984, 0.96707361, 0.08055644],
       [0.14331784, 0.66327956, 0.19808327, 0.13037875, 0.39409928]])

**choice**: method generates a random sample froma given 1-D array.

random.RandomState.choice(a, size= None, replace= True, p= None)

- a: 1-D array-like or int
- size: int or tuple of ints (default = None)
- replace: boolean output. this ensures whether a sample is with or without replacement. Default is True, meaning that a value of "a" can be selected multiple times.
- p: 1-D array specifying probabilities of occurrence of each element (default = uniform distribution over all values of a)

In [ ]:
a = ["Maths", "Python", "SQL", "Excel", "Powerbi", "Tableau", "Statistics", "Public policy analysis", "Operations Reasearch", "Risk Management"]

for i in range(3):
    print(prng.choice(a, size = 3, replace = True))

['Excel' 'Public policy analysis' 'Python']
['Tableau' 'SQL' 'Public policy analysis']
['Python' 'Tableau' 'Risk Management']


In [ ]:
pd.DataFrame(prng.choice(a, size = (3,3), replace = True), columns = ["s1", "s2", "s3"])

s1                      s2               s3
0                   Maths         Risk Management           Python
1  Public policy analysis                 Tableau  Risk Management
2                   Maths  Public policy analysis       Statistics

**bytes**: method returns random bytes

In [ ]:
prng.bytes(10)

b'\x7f\xd1xzx\x1b0=\xa7\x8f'

**identity**: method returns an identity matrix/ square matrix of the size provided.

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Indexing and Slicing arrays ##

Indexing and slicing NumPy arrays is done as we do Pandas dataframes, Pandas series and lists.

In [ ]:
#Initialising a numpy array#
array = np.random.randint(low = 256, high = 324, size = (8, 2))
array

array([[259, 295],
       [312, 316],
       [320, 292],
       [300, 267],
       [287, 298],
       [270, 322],
       [296, 270],
       [304, 271]])

In [ ]:
#Slicing#
array[1, :]

array([312, 316])

In [ ]:
#accessing elements#
array[1,0]

312

In [ ]:
#accessing first three elements#
array[:3]

array([[259, 295],
       [312, 316],
       [320, 292]])

In [ ]:
#accessing second column of the array#
col2 = array[:, 1].reshape(-1,1)
#accessing first column of the array#
col1 = array[:, 0].reshape(-1,1)
#creating an array with columns interchanged#
rev = np.concatenate((col2, col1), axis = 1)
rev

array([[295, 259],
       [316, 312],
       [292, 320],
       [267, 300],
       [298, 287],
       [322, 270],
       [270, 296],
       [271, 304]])

**np.vstack()** & **np.hstack()**: In addition to the np.concatenate() function, NumPy provides two functions that can be used to concatenate 2d arrays. These functions are specifically designed for vertical and horizontal concatenation, respectively.


In [ ]:
np.vstack((col2, col1))

array([[295],
       [316],
       [292],
       [267],
       [298],
       [322],
       [270],
       [271],
       [259],
       [312],
       [320],
       [300],
       [287],
       [270],
       [296],
       [304]])

In [ ]:
arrbm = np.hstack((col2, col1))
arrbm

array([[295, 259],
       [316, 312],
       [292, 320],
       [267, 300],
       [298, 287],
       [322, 270],
       [270, 296],
       [271, 304]])

## Boolean Mask ##

One of the most powerful concepts in NumPy is Boolean masking.
- We can subset the NumPy array based on a logical true false condition and get the output as the elements which satisy that condition.

In [ ]:
arrbm

array([[295, 259],
       [316, 312],
       [292, 320],
       [267, 300],
       [298, 287],
       [322, 270],
       [270, 296],
       [271, 304]])

**logical_or**: Perform element wise logical OR operation on arrays and returns an array with true and false values at respective indexes.
- np.logical_or accepts only two arrays and not more so for performing multiple operations nesting can be used.
- np.logical_or( x, y , out = None, where = True)

In [ ]:
np.logical_or(arrbm % 5 == 0 , arrbm % 3 == 0)

array([[ True, False],
       [False,  True],
       [False,  True],
       [ True,  True],
       [False, False],
       [False,  True],
       [ True, False],
       [False, False]])

In [ ]:
arrbm[~np.logical_or(arrbm % 16 == 0, np.logical_or(arrbm % 18 == 0, arrbm % 5 == 0))]

array([259, 316, 312, 292, 267, 298, 287, 322, 296, 271])

In [ ]:
arrbm[np.logical_or(arrbm % 16 == 0, np.logical_or(arrbm % 18 == 0, arrbm % 5 == 0))]

array([295, 320, 300, 270, 270, 304])

In [ ]:
arrbm[((arrbm % 16 == 0) | (arrbm % 5 == 0))]

array([295, 320, 300, 270, 270, 304])

In [ ]:
arrbm[((arrbm % 16 == 0) | (arrbm % 5 == 0) | (arrbm % 18 == 0))]

array([295, 320, 300, 270, 270, 304])

**logical_and**: performs element wise logical_and operation on two numpy arrays and returns a NumPy array with true and false values at respective indexes.

In [ ]:
arrbm[np.logical_and(arrbm % 16 == 0, arrbm % 5 == 0)]

array([320])

In [ ]:
arrbm[((arrbm % 16 == 0) & (arrbm % 5 == 0))]

array([320])

In [ ]:
arrbm[((arrbm % 3 == 0) & (arrbm % 5 == 0) & (arrbm % 18 == 0))]

array([270, 270])

### Accessing/Changing specific elements, rows, columns ets. ###

In [ ]:
a = np.random.randint(1, 15, (2, 7))
a

array([[ 3,  1, 12,  5,  4,  2, 12],
       [ 9,  7,  6,  8,  5,  6,  6]])

In [ ]:
# Get a specific element
a[1, 5]

6

In [ ]:
# Get a specific row
a[1,:]

array([9, 7, 6, 8, 5, 6, 6])

In [ ]:
# Get a specific column
a[:, 2]

array([12,  6])

In [ ]:
# [start_idx: end_idx : stepsize]
a[0, 1:-1:2]

array([1, 5, 2])

In [ ]:
# modifying elements
a[0, :] = np.random.randint(0, 100, (7))
a

array([[61,  3, 87, 30, 37, 51, 13],
       [ 9,  7,  6,  8,  5,  6,  6]])

In [ ]:
np.random.randint(0, 100, (7, 1))

array([[77],
       [63],
       [ 2],
       [11],
       [29],
       [74],
       [27]])

**Creating a padded array using indexing and slicing**

In [ ]:
array = np.ones((5,5))
print(array)
z = np.zeros((3,3))
z[1,1] = 9
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [ ]:
array[1:4, 1:4] = z
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Copying arrays ####

In [ ]:
a = np.array([1, 2, 3])
b = a
b[0] = 100
a

array([100,   2,   3])

NumPy array can not be copied by using assignment operators as it creates a referenced instance of the same array and any change to the value of the new array would automatically be reflected in the source array. So, for copying arrays **np.copy** can be used.

**.copy()**: copies contents of one array to a new array

In [ ]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print("a = ", a, "\n&\nb = ", b, "\nevidently changes made in b are not being reflected in a")

a =  [1 2 3] 
&
b =  [100   2   3] 
evidently changes made in b are not being reflected in a


## Mathematical Operations ##

In [ ]:
a = np.arange(1, 5)
a

array([1, 2, 3, 4])

In [ ]:
a + 2
a

array([1, 2, 3, 4])

In [ ]:
a - 2

array([-1,  0,  1,  2])

In [ ]:
a * 2

array([2, 4, 6, 8])

In [ ]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [ ]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [ ]:
b = np.array([0 if i%2 == 0 else 1 for i in range(1, 5)])
a + b

array([2, 2, 4, 4])

In [ ]:
a * b

array([1, 0, 3, 0])

In [ ]:
a ** b

array([1, 1, 3, 1], dtype=int32)

In [ ]:
b / a

array([1.        , 0.        , 0.33333333, 0.        ])

### Linear Algebra ###

In [ ]:
a = np.ones((2, 3), dtype = 'int16')
b = np.full((3, 2), 2)
np.matmul(a, b)

array([[6, 6],
       [6, 6]])

In [ ]:
c = np.identity(3)
np.linalg.det(c)

1.0

### Statistics ###

In [ ]:
stats = np.random.randint(1, 7, (2, 3))
stats

array([[4, 4, 1],
       [2, 6, 3]])

In [ ]:
# axis = 1 for rows and 0 for columns
np.min(stats, axis = 1)
# returns minimum values in rows

array([1, 2])

In [ ]:
np.max(stats, axis = 0)
# returns maximum values in columns

array([4, 6, 3])

In [ ]:
np.sum(stats, axis = 1)
# sum of rows

array([ 9, 11])

In [ ]:
np.mean(stats, axis = 0)
# mean of columns

array([3., 5., 2.])